Rails.application.routes.draw do
  get 'fyrb_statements/index'
  get 'fyrb_statements/show'
  get 'fyrb_statements/create'
  get 'fyrb_statements/update'
  get 'fyrb_statements/destroy'
  get 'fyrb_terms/index'
  get 'fyrb_terms/show'
  get 'fyrb_terms/create'
  get 'fyrb_terms/update'
  get 'fyrb_terms/destroy'
  get 'fyrb_fragments/index'
  get 'fyrb_fragments/show'
  get 'fyrb_fragments/create'
  get 'fyrb_fragments/update'
  get 'fyrb_fragments/destroy'
  get 'fyrb_tools/index'
  get 'fyrb_tools/show'
  get 'fyrb_tools/create'
  get 'fyrb_tools/update'
  get 'fyrb_tools/destroy'
  get 'fyrb_tags/index'
  get 'fyrb_tags/show'
  get 'fyrb_tags/create'
  get 'fyrb_tags/update'
  get 'fyrb_tags/destroy'
  get 'fyrb_microposts/index'
  # get 'hello/index'
  root 'hello#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :fyrb_users, param: :_username
  post '/auth/login', to: 'fyrb_auths#login'
  resources :fyrb_microposts
  get '/*a', to: 'fyrb_auths#not_found'
end
