const constants = {
    ADD_NUM: "ADD_NUM",
    REDUCE_NUM: "REDUCE_NUM",
    // Fetch Astronauts
    ADD_ASTRONAUTS_FETCH_START: "ADD_ASTRONAUTS_FETCH_START",
    ADD_ASTRONAUTS_FETCH_SUCCESS: "ADD_ASTRONAUTS_FETCH_SUCCESS",
    ADD_ASTRONAUTS_FETCH_FAUILE: "ADD_ASTRONAUTS_FETCH_FAUILE",
    // USERS
    USER_SIGNOUT: "USER_SIGNOUT",
    USER_RESTORE: "USER_RESTORE",
    USER_NATIVE_DATA: "USER_NATIVE_DATA",
    ADD_MENU: "ADD_MENU",
    REMOVE_MENU: "REMOVE_MENU",
    CLEAR_MENU: "CLEAR_MENU",

    // Settings
    SETTINGS_SET_CONTAINER_DIMENSIONS: "SETTINGS_SET_CONTAINER_DIMENSIONS",
    SETTINGS_SET_CONTAINER_THEME_COLOR: "SETTINGS_SET_CONTAINER_THEME_COLOR",
    SETTINGS_SET_SELECTED_ITEM: "SETTINGS_SET_SELECTED_ITEM",
    SETTINGS_SET_PARSING_WORDS_SERVICE_ITEM: "SETTINGS_SET_PARSING_WORDS_SERVICE_ITEM",

}

export default constants