const constants = {
    ADD_NUM: "ADD_NUM",
    REDUCE_NUM: "REDUCE_NUM",
    // Fetch Astronauts
    ADD_ASTRONAUTS_FETCH_START: "ADD_ASTRONAUTS_FETCH_START",
    ADD_ASTRONAUTS_FETCH_SUCCESS: "ADD_ASTRONAUTS_FETCH_SUCCESS",
    ADD_ASTRONAUTS_FETCH_FAUILE: "ADD_ASTRONAUTS_FETCH_FAUILE",
    // USERS
    USER_SIGNOUT: "USER_SIGNOUT",
}

export default constants